# config.yaml

method:
  name: "SAFECHUNK"
  lr: 0.0001
  optimizer: "adamw"
  lr_scheduler: "cosine"
  num_warmup_steps: 0
  history_len: 8
  chunk_len: 5
  m_steps: 3
  safety_delta: 0.12
  use_safety_token: true
  final_dim: 256
  voxel_sizes: [100]
  rotation_resolution: 5

rlbench:
  task_name: "multi"
  tasks: ["open_drawer", "slide_block_to_color_target"]
  demo_path: "/my/demo/path"
  episode_length: 25
  cameras: ["front", "left_shoulder", "right_shoulder", "wrist"]
  camera_resolution: [128, 128]
  scene_bounds: [-0.3, -0.5, 0.6, 0.7, 0.5, 1.6]
  include_lang_goal_in_obs: true
  time_in_state: true
  headless: true

framework:
  tensorboard_logging: true
  csv_logging: true
  gpu: 0
  logdir: "/tmp/arm_test/"
  start_seed: 0
  record_every_n: 5

  eval_envs: 1
  eval_from_eps_number: 0
  eval_episodes: 25
  eval_type: "missing"   # or "best"
  eval_save_metrics: true

cinematic_recorder:
  enabled: false
  camera_resolution: [1280, 720]
  fps: 30
  rotate_speed: 0.005
  save_path: "/tmp/videos/"

